---
title: "git_01"
author: "Bethanee Olmos"
date: "September 2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Build a Poem with commits to different branches
Our project will be done using a sequence of save and commits and branch actions.
<!-- Do not modify or change any text in "!--" bracketed areas such as this --- these are instructions to
you, if you change any of this the git program will notice it and compromise your git merging strategy !-->

## First Verse 
<!--Put the first five lines of a poem by Lewis Carrol in this section!-->

five little girls of five, four, three,  
two, one:  
rolling on the hearthrug, full of tricks  
and fun.  
Five rosey girls, in years from ten to six:  

## Second Verse
<!--Put the first five lines of a poem by Robert Frost here!-->
The city had withdrawn into itself
and left atlast the country to the country;  
when between whirls of snow not come to lie  
And whirls of foliage not yet laid, there drove  
A stranger to our yard, who looked the city,  


## Third Verse
<!--Put the first two verses of The Walrus and the Carpenter here!-->
 The sun was shining on the sea,  
 shining with all his might:  
 he did his very best to make the billows smooth and bright-  
 and this was odd, because it was  
 the middle of the night.
 The moon was shining sulkily,  
 because she thought the sun  
 had got not business to be there  
 after the day was done-  
 "It's very rude of him," she said,"to come and spoil the fun."  


## Last Verse
<!--Put a short poem of your choice 8-20 lines,here!-->
If you always try your best  
then you'll never have to wonder  
about what you could have done  
if you'd summoned all your thunder.  
And if your best  
was not as good  
as you hoped it would be,  
you still could say,  
"i gave today  
all that i had in me."  